package com.devmmurray.firebaseshop.utils

enum class LoginState {
    FIRST_NAME_ERROR,
    LAST_NAME_ERROR,
    EMAIL_ERROR,
    PASSWORD_ERROR,
    PASSWORD_MATCH_ERROR,
    LOGGING_IN,
    LOG_IN_ERROR,
    IS_REGISTERING,
    REGISTRATION_ERROR,
    PASSWORD_RESET_ERROR,
    PASSWORD_RESET_SUCCESS,
    SUCCESS
}